[project]
name = "human_loop"
version = "0.0.1"
description = "A simple example to get started with human-in-the-loop using the restack-ai python library"
authors = [{ name = "Restack Team", email = "service@restack.io" }]
requires-python = ">=3.10,<4.0"
readme = "README.md"
dependencies = [
    "restack-ai>=0.0.48,<0.0.49",
    "watchfiles>=1.0.0,<2",
]

[project.scripts]
dev = "src.services:watch_services"
services = "src.services:run_services"
schedule = "schedule_workflow:run_schedule_workflow"

[dependency-groups]
dev = ["pytest==6.2"]
