[tool.poetry]
name = "llama_quickstart"
version = "0.0.1"
description = "A quickstart example showcasing streamlit, fastapi, togetherai and llamaindex"
authors = [
    "Restack Team <service@restack.io>",
]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydantic = "^2.10.3"
restack-ai = "^0.0.48"
fastapi = "0.115.4"
llama-index = "0.11.22"
llama-index-llms-together = "0.2.0"
uvicorn = "0.32.0"
python-dotenv = "1.0.1"
streamlit = "1.40.0"
requests = "2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
services = "src.services:run_services"
app = "src.app:run_app"
