[project]
name = "fastapi_togetherai_llama"
version = "0.0.1"
description = "A simple example showcasing fastapi, togetherai and llamaindex"
authors = [{ name = "Restack Team", email = "service@restack.io" }]
requires-python = ">=3.10,<4.0"
readme = "README.md"
dependencies = [
    "fastapi==0.115.4",
    "llama-index==0.11.22",
    "llama-index-llms-together==0.2.0",
    "uvicorn==0.32.0",
    "python-dotenv==1.0.1",
    "restack-ai>=0.0.48,<0.0.49",
]

[project.scripts]
services = "src.services:run_services"
app = "src.app:run_app"
