[project]
name = "flask_togetherai_llamaindex"
version = "0.0.1"
description = "A simple example to demonstrate usage TogetherAI and LlamaIndex"
authors = [{ name = "Restack Team", email = "service@restack.io" }]
requires-python = ">=3.10,<4.0"
readme = "README.md"
dependencies = [
    "python-dotenv==1.0.1",
    "llama-index==0.11.22",
    "llama-index-llms-together==0.2.0",
    "flask[async]==3.0.3",
    "flask-cors==5.0.0",
    "restack-ai>=0.0.48,<0.0.49",
]

[project.scripts]
services = "src.services:run_services"
flask = "src.app:run_flask"
